### ISSUE TITLE
Updating for Swift 2

### ISSUE THREAD

**Issue by ricburton** [cabotmoose/plaid-swift#1]
Hi @cabotmoose,

Thanks so much for putting this together! I’ve made a start at moving this over to Swift 2 and I’d love your help.

In particular, I think that I’m not correctly handling empty responses from the API here: https://github.com/ricburton/plaid-swift/blob/master/Plaid.swift#L284
And in other places.

`Type` is now a reserved word in Swift so I changed it to `ProductType`: https://github.com/ricburton/plaid-swift/blob/master/Plaid.swift#L35

There is a typo here where **instiution** should be institution: https://github.com/cabotmoose/plaid-swift/blob/master/Plaid.swift#L140

Did you use this library for an app you are working on? If so, I’d love to know which one.

Cheers,

Richard

**Comment by istx25** [comment]
What's the status on this? How's it coming?

**Comment by cabotmoose** [comment]
Thanks for reaching out Richard! 

Planning on pushing out updated Swift 2 code this weekend, will definitely take a look at your code. Good catch on the typo, will be sure to fix as well. 

Not currently using this particular code in an app, but hopefully will for an upcoming app that I'll be working on.

**Comment by ricburton** [comment]
Thanks @cabotmoose! I’d love to hear more about what you’re working on and show you the app I’m making.

@istx25 I just pushed up my hacky-but-working version that I’ve been using for prototyping with Swift 2.

**Comment by cabotmoose** [comment]
Latest commit should fix Swift 2 issues
